plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.4.2
  NewCops: enable
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "log/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Style/AsciiComments:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - hash
    - array
